_wandb:
    value:
        cli_version: 0.27.0
        e:
            ux7yb8uag27c0w64ciovgjhyzatitomb:
                args:
                    - --paired_dir
                    - ./eval_outputs/baseline_output_official_test/paired_data
                    - --csv
                    - cxr_data/mimic_cxr_official_test.csv
                    - --output_dir
                    - ./eval_outputs/labeldot
                    - --query_mode
                    - all
                    - --batch_size
                    - "128"
                    - --skip_existing
                    - --wandb-project
                    - mimic-cxr-clip
                    - --wandb-run-name
                    - labeldot
                    - --wandb-entity
                    - tomererez1998-technion-israel-institute-of-technology
                codePath: baseline_eval/run_all_evals.py
                codePathLocal: baseline_eval/run_all_evals.py
                cpu_count: 44
                cpu_count_logical: 88
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "249792131072"
                        used: "14873210880"
                email: tomererez1998@gmail.com
                executable: /home/tomererez/miniconda3/envs/thesis_clip/bin/python
                git:
                    commit: 65bcf3b144ca1367644259aaf425cc4838fc3696
                    remote: https://github.com/tomer-erez/normal_near_normal.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-09593c50-07a1-2e88-a076-2ef0ed13e8bc
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-f87f94f4-b111-f865-49da-cbe0fc07b81b
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-e48f7fcd-bc9b-4bae-75b8-2604762121f3
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-afb98133-999a-bac2-536c-999ff066e62d
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-8783c7ea-025b-aa21-3574-63700f58f6a5
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-78bb497d-45ee-2f38-8712-dc0daf7f42bc
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-6254a87e-063d-c966-b0c2-266d94dd62e8
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-92e16a99-0c37-3a53-3704-a2f758102e9e
                host: floria
                memory:
                    total: "473239162880"
                os: Linux-6.8.0-117-generic-x86_64-with-glibc2.39
                program: /home/tomererez/normal_near_normal/baseline_eval/run_all_evals.py
                python: CPython 3.11.15
                root: eval_outputs/labeldot
                startedAt: "2026-06-12T09:46:42.676674Z"
                writerId: ux7yb8uag27c0w64ciovgjhyzatitomb
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.15
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
batch_size:
    value: 128
csv:
    value: cxr_data/mimic_cxr_official_test.csv
max_samples:
    value: null
output_dir:
    value: ./eval_outputs/labeldot
paired_dir:
    value: ./eval_outputs/baseline_output_official_test/paired_data
query_mode:
    value: all
skip_existing:
    value: true
wandb_entity:
    value: tomererez1998-technion-israel-institute-of-technology
wandb_project:
    value: mimic-cxr-clip
wandb_run_name:
    value: labeldot
